language: node_js
dist: trusty
node_js:
  - "7"
install:
  - npm install hexo-cli -g
  - npm install gulp -g
  - cd _hexo
  - npm install
  - npm install hexo-prism-plugin@2.1.0 --save
script:
  - chmod +x ../patch.sh
  - chmod +x ../deploy.sh
  - ../patch.sh > /dev/null
  - hexo clean
  - hexo g
  - gulp
  - ../deploy.sh > /dev/null
branches:
  only:
    - raw
